### ISSUE TITLE
StackOverflowError while executing scripts with no commands before the <tearDown>

### ISSUE THREAD

**Issue by SonOfFlyingPig** [FINRAOS/JTAF-XCore#4]
Scripts that consist entirely of a <tearDown> block crash because of a StackOverflowError. Scripts with <tearDown>'s are converted to TryRecoverCleanup commands and from a preliminary analysis it looks like the empty <try> block is executing itself over and over again.

This happens whether or not the <tearDown> itself contains any commands.

(Partial) Stack trace:

java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.finra.jtaf.core.model.execution.Interpreter.getInvocationTarget(Interpreter.java:273)
	at org.finra.jtaf.core.model.execution.Interpreter.visitInvocation(Interpreter.java:233)
	at org.finra.jtaf.core.model.invocationtarget.Command.executeInvocation(Command.java:460)
	at org.finra.jtaf.core.commands.Block.execute(Block.java:66)
	at org.finra.jtaf.core.model.invocationtarget.Command.launch(Command.java:97)
	at org.finra.jtaf.core.model.execution.Interpreter.visitCommand(Interpreter.java:195)
	at org.finra.jtaf.core.model.invocationtarget.Command.acceptInvocationTargetVisitor(Command.java:438)
	at org.finra.jtaf.core.model.execution.Interpreter.visitInvocation(Interpreter.java:235)
	at org.finra.jtaf.core.model.invocationtarget.Command.executeInvocation(Command.java:460)
	at org.finra.jtaf.core.commands.Block.execute(Block.java:66)
	at org.finra.jtaf.core.model.invocationtarget.Command.launch(Command.java:97)
	at org.finra.jtaf.core.model.execution.Interpreter.visitCommand(Interpreter.java:195)
	at org.finra.jtaf.core.model.invocationtarget.Command.acceptInvocationTargetVisitor(Command.java:438)
	at org.finra.jtaf.core.model.execution.Interpreter.visitInvocation(Interpreter.java:235)
	at org.finra.jtaf.core.model.invocationtarget.Command.executeInvocation(Command.java:460)
	at org.finra.jtaf.core.commands.Block.execute(Block.java:66)
	at org.finra.jtaf.core.model.invocationtarget.Command.launch(Command.java:97)
	at org.finra.jtaf.core.model.execution.Interpreter.visitCommand(Interpreter.java:195)
	at org.finra.jtaf.core.model.invocationtarget.Command.acceptInvocationTargetVisitor(Command.java:438)
	at org.finra.jtaf.core.model.execution.Interpreter.visitInvocation(Interpreter.java:235)
	at org.finra.jtaf.core.model.invocationtarget.Command.executeInvocation(Command.java:460)
	at org.finra.jtaf.core.commands.Block.execute(Block.java:66)

**Comment by SonOfFlyingPig** [comment]
Having a script that's entirely a <tearDown> block doesn't really make sense anyway, so fortuntaely this bug isn't huge.

**Comment by snoopysnake** [comment]
No commands in a test's teardown will cause the whole test (containing empty teardown) to repeat infinitely 
![image](https://cloud.githubusercontent.com/assets/7180497/16087269/699d5048-32f0-11e6-9946-fdd50d2e52e6.png)
